info:
  app:
    name: dps-multi-module-starterkit-java
    description: Java API Starter from Template

management:
  # TODO: Figure out the proper security for these, and perhaps don't expose everything
  endpoints.web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    enabled: true
    distribution:
      percentiles.http.server.requests: 0.5, 0.90, 0.95, 0.99, 0.999
      percentiles-histogram.http.server.requests: true
      sla.http.server.requests: 10ms, 50ms
      slo.http.server.requests: 10ms, 50ms
    tags:
      group: starter
      service: example
      region: "${POD_REGION:local}"
      stack: "${CLUSTER:dev}"
      ns: "${NAMESPACE:example}"
      pod: "${POD_ID:docker}"
    web.server.request.autotime.enabled: true
  server.port: 8081

# Setting up K8 health probes - with health probes set to true you can use
# the paths in your config like the snippet below

#livenessProbe:
#  httpGet:
#    path: /actuator/health/liveness
#    port: 8081
#  failureThreshold: ...
#  periodSeconds: ...
#
#readinessProbe:
#  httpGet:
#    path: /actuator/health/readiness
#    port: 8081
#  failureThreshold: ...

server:
  tomcat:
    basedir: build/tomcat
    max-threads: 100
  ssl:
    enabled: false
  port: 8080

spring:
  application:
    name: "starter-api"

  datasource:
#    platform: h2
    url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS example\;SET SCHEMA example;
    username: skuser
    password: localT3st!
    hikari:
      jdbc-url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS example\;SET SCHEMA example;
      username: skuser
      password: localT3st!
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      org.hibernate.envers.audit_table_suffix: _audit
      org.hibernate.envers.revision_field_name: revision_id
      org.hibernate.envers.revision_type_field_name: type
      org.hibernate.envers.global_with_modified_flag: true
      org.hibernate.envers.store_data_at_delete: true
      hibernate:
        generate_statistics: false
        jdbc.lob.non_contextual_creation: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      force: true
  kafka:
    bootstrap-servers: "localhost:9092"
    topic.name: default-kafka-topic
    replication.factor: 1
    partition.number: 1
    consumer:
      auto-offset-reset: earliest
      #client-id: "${pod.name}_${pod.namespace}_${pod.id}"
      group-id: starter
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: io.twdps.starter.boot.kafka.CustomJsonDeserializer
      level.concurrency: 1
      properties:
        spring.json.trusted.packages: io.twdps.starter.*
        spring.json.value.default.type: io.twdps.starter.boot.notifier.EntityLifecycleNotification
    producer:
      # This means the leader will wait for the full set of in-sync replicas to acknowledge
      # the record. This guarantees that the record will not be lost as long as at least one
      # in-sync replica remains alive. This is the strongest available guarantee.
      # This is equivalent to the acks=-1 setting. For an eventing architecture this should be
      # our default setting - no need for extremely high speed compromises here.
      acks: all
      batch-size: 1048576
      buffer-memory: 2097152
      #client-id: "${pod.name}_${pod.namespace}_${pod.id}"
      compression-type: lz4
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: io.twdps.starter.boot.kafka.CustomJsonSerializer
      properties:
        max.in.flight.requests.per.connection: 2
        spring.json.value.default.type: io.twdps.starter.boot.notifier.EntityLifecycleNotification

opentracing:
  zipkin:
    enabled: true
    http-sender.baseUrl: http://zipkin.istio-system.svc.cluster.local:9411

springdoc:
  writer-with-default-pretty-printer: true
  show-actuator: true
  swagger-ui:
    operations-sorter: method
    path: swagger

starter:
  openapi:
    authUrl: https://iam.twdps.io/whoami
    default-oauth-security-scheme: true
    default-jwt-bearer-security-scheme: true
    license: MIT License
    title: Example service
    description: Example service providing Account info
    version: v1
    licenseUrl: https://github.com/thoughtworks-dps/dps-multi-module-starterkit-java/blob/master/LICENSE
    contactEmail: starter-java@example.com
    contactUrl: https://example.twdps.io/
    contactName: Example
    serverUrl: http://localhost:8080
  boot:
    kafka-lifecycle-notifier:
      enabled: true
      producer:
        topic.name: example-entity-lifecycle
        replication.factor: 1
        partition.number: 1
      consumer:
        topic.name: example-entity-lifecycle
        level.concurrency: 1

opa:
  filter:
    enabled: true
    document-path: authz
    instance: http://opa:8181
    endpoints-whitelist: /actuator/**,/swagger*/**,/v3/api-docs/**
